name: CI_PUSH

on:
  push:
    branches: [ dev, brian ]
    # TO BE CHANGED since it should be the branch you're working on

defaults:
  run:
    working-directory: source
jobs:
  HTMLHint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npx htmlhint ./HTML/settings-page.html
  Stylelint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npx stylelint **/*.css
  ESlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npx eslint ./JS/*.js
  JSDocs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo npx jsdoc ./JS -r -d ./docs
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs

