name: CI_PUSH

on:
  push:
    branches: [dev , tommy, brian, FrankLi-break_page, Iain, how-to-page, set-up-page, try-cypress]
    # TO BE CHANGED since it should be the branch you're working on

defaults:
  run:
    working-directory: source
jobs:
  HTMLHint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npx htmlhint ./HTML/*.html
  Stylelint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npx stylelint ./*.css
  ESlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npx eslint ./JS/*.js
  GenerateElectronApp:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    # - run: rm -r wepomo-win32-x64.zip
    - run: npx electron-packager . wepomo --overwrite --electron-version=12.0.0 --platform=win32 --icon "./logo/logo.ico"
    - run: zip -r wepomo-win32-x64.zip wepomo-win32-x64
    - run: rm -r wepomo-win32-x64
  Jest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm run test
