name: CI_PUSH

on:
  push:
    branches: [dev , tommy, brian, franklee, frankli, Iain, how-to-page, set-up-page, try-cypress]
    # TO BE CHANGED since it should be the branch you're working on

defaults:
  run:
    working-directory: source
jobs:
  HTMLHint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npx htmlhint ./HTML/*.html
  Stylelint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npx stylelint ./*.css
  ESlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npx eslint ./JS/*.js
  GenerateElectronApp:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        npx electron-packager . wepomo --overwrite --electron-version=12.0.0 --platform=win32 --icon "./logo/logo.ico"
        tar.exe -a -c -f wepomo-win32-x64.zip wepomo-win32-x64
    - name: Commit zip file
      run: |
        git config --global user.email "totran@ucsd.edu"
        git config --global user.name "group20"
        git add wepomo-win32-x64.zip
        git commit -m "update Electron app" -a
    - name: Deploy Electron App
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
        branch: ${{ github.HEAD_REF }}