name: CI_PULL

on:
  pull_request:
    branches: [ dev ]
    # TO BE CHANGED since it should be the branch you're working on


defaults:
  run:
    working-directory: source
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run test
  HTMLHint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npx htmlhint ./HTML/*.html
  ESlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npx eslint ./JS/*.js
