name: DOCUMENTATION_GENERATION

on:
  push:
    branches: [ main ]
    # TO BE CHANGED since it should be the branch you're working on

defaults:
  run:
    working-directory: source
jobs:
  JSDocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo npx jsdoc ./JS -r -d ./out
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: docs
          publish_dir: ./source/out

